image:
  file: .gitpod.Dockerfile

additionalRepositories:
  - url: https://github.com/ben-manes/caffeine
    checkoutLocation: caffeine

tasks:
  - init: |
      if [ "$GITPOD_HEADLESS" = "true" ]; then
        export TERM=dumb
      fi

      ./gradlew build
vscode:
  extensions:
    - vscjava.vscode-java-pack
    - redhat.vscode-xml
